### PR TITLE
Switch to mod_wsig-express

### LINKED ISSUE #1274: Service pod errors out on Fedora 35
```
Exception occurred processing WSGI script '/usr/share/packit/packit.wsgi'.
Traceback (most recent call last):
[Tue Nov 09 13:09:12.867761 2021] [wsgi:error]   File "/usr/share/packit/packit.wsgi", line 1, in <module>
[Tue Nov 09 13:09:12.867766 2021] [wsgi:error]    from packit_service.service.app import application
[Tue Nov 09 13:09:12.867772 2021] [wsgi:error]   File "/usr/local/lib/python3.10/site-packages/packit_service/service/app.py", line 14, in <module>
[Tue Nov 09 13:09:12.867776 2021] [wsgi:error]     from packit_service.log_versions import log_service_versions
[Tue Nov 09 13:09:12.867781 2021] [wsgi:error]   File "/usr/local/lib/python3.10/site-packages/packit_service/log_versions.py", line 10, in <module>
[Tue Nov 09 13:09:12.867785 2021] [wsgi:error]    from flask_restx import __version__ as restx_version
[Tue Nov 09 13:09:12.867790 2021] [wsgi:error]   File "/usr/lib/python3.10/site-packages/flask_restx/__init__.py", line 4, in <module>
[Tue Nov 09 13:09:12.867792 2021] [wsgi:error]     from . import fields, reqparse, apidoc, inputs, cors
[Tue Nov 09 13:09:12.867795 2021] [wsgi:error]   File "/usr/lib/python3.10/site-packages/flask_restx/reqparse.py", line 19, in <module>
[Tue Nov 09 13:09:12.867798 2021] [wsgi:error]     from .model import Model
[Tue Nov 09 13:09:12.867801 2021] [wsgi:error]  File "/usr/lib/python3.10/site-packages/flask_restx/model.py", line 21, in <module>
[Tue Nov 09 13:09:12.867804 2021] [wsgi:error]     from jsonschema import Draft4Validator
[Tue Nov 09 13:09:12.867807 2021] [wsgi:error]  File "/usr/lib/python3.10/site-packages/jsonschema/__init__.py", line 21, in <module>
[Tue Nov 09 13:09:12.867811 2021] [wsgi:error]    from jsonschema._types import TypeChecker
[Tue Nov 09 13:09:12.867815 2021] [wsgi:error]  File "/usr/lib/python3.10/site-packages/jsonschema/_types.py", line 168, in <module>
[Tue Nov 09 13:09:12.867818 2021] [wsgi:error]    draft3_type_checker = TypeChecker(
[Tue Nov 09 13:09:12.867829 2021] [wsgi:error]  TypeError: TypeChecker() takes no arguments
```

May be related to [bumping Fedora version in the base image](https://github.com/packit/deployment/pull/276).

### PR DESCRIPTION
**Pull request by csomh**
Resolves #1274.

### CODE REVIEW

File: files/run_httpd.sh [hunk 1]
```diff
@@ -1,19 +1,31 @@
...
   sleep 2
 done
-popd  # pushd /src
 
-httpd -DFOREGROUND
+# If the number of attempts was exhausted: the migration failed.
+# Exit with an error.
+if [[ $n -eq $ATTEMPTS ]]; then
+    exit 1
+fi
```
Comment (lachmanfrantisek) [inline files/run_httpd.sh:19]: Can we echo that the migration fails so it's visible in the logs?

**Review by lachmanfrantisek — APPROVED** [review]
Wow, thanks!

**Review by TomasTomecek — APPROVED** [review]
haven't tested locally, changes LGTM

File: files/run_httpd.sh (hunk 1 above)
Comment (csomh) [reply files/run_httpd.sh]: Added an error message.

**Comment by csomh** [comment]
Note: I've added the `--access-log` option, to better resemble the current configs.

File: files/install-deps.yaml [hunk 2]
```diff
@@ -13,8 +13,6 @@
           - python3-click
           - git # setuptools-scm
           # httpd & deps
-          - httpd
-          - mod_md
           - mod_ssl
           - nss_wrapper
```
Comment (jpopelka) [inline files/install-deps.yaml:17]: I think the `nss_wrapper` is needed only in `setup_env_in_openshift.sh` so can perhaps be removed as well.

**Review by jpopelka — APPROVED** [review]
well done sir :1st_place_medal:

File: files/install-deps.yaml (hunk 2 above)
Comment (csomh) [reply files/install-deps.yaml:17]: I wanted to do just that, but then it turned out that `setup_env_in_openshift.sh` is also used in [`run_worker.sh`](https://github.com/packit/packit-service/blob/7011396a299e7addc7328ac7980f8bf21d09c82a/files/run_worker.sh#L9) and [`run_tests.sh`](https://github.com/packit/packit-service/blob/7011396a299e7addc7328ac7980f8bf21d09c82a/files/run_tests.sh#L5). If I'm not mistaken it's required by `fedpkg` and other tooling. It might be possible to get rid of it, but I would do that in some other PR :smiley:

**Comment by csomh** [comment]
I'll merge this after the `stable` branch is moved.

File: files/install-deps.yaml (hunk 2 above)
Comment (jpopelka) [reply files/install-deps.yaml:17]: > setup_env_in_openshift.sh is also used in run_worker.sh and run_tests.sh

Yes, but there's a separate [install-deps-worker.yaml](https://github.com/packit/packit-service/blob/main/files/install-deps-worker.yaml#L12) for them. 

> it's required by fedpkg and other tooling

I don't see anything in `dnf repoquery --whatrequires nss_wrapper` output on my machine.

Comment (csomh) [reply files/install-deps.yaml]: Removed. Thanks!

**Comment by csomh** [comment]
recheck

**Comment by csomh** [comment]
regate
